<?php

use \App\Models\Module;

return [
    'name' => 'Payroll',
    'url' => 'payroll',
    'scope' => json_encode([Module::SCOPE_ADMIN, Module::SCOPE_COMPANY]),
    'icon' => 'fa fa-credit-card-alt',
    'status' => 1,
    'order' => 7,

    //Submodules
    'submodules' => [
        [
            'name' => 'Salary Structure Components',
            'show' => 0,
            'scope' => json_encode([Module::SCOPE_COMMON]),
            'order' => 2,
            'status' => 1,
            'menu' => [
                [
                    'name' => 'New Component',
                    'url' => 'structure/add',
                    'action' => 'add',
                    'show' => 0,
                    'order' => 1,
                    'status' => 1,
                ],
                [
                    'name' => 'Salary Structure Components',
                    'url' => 'structures',
                    'action' => 'list',
                    'show' => 1,
                    'order' => 2,
                    'status' => 1,
                ],
                [
                    'name' => 'Edit Salary Structure Component',
                    'url' => 'structure/edit',
                    'action' => 'edit',
                    'show' => 0,
                    'order' => 3,
                    'status' => 1,
                ],
                [
                    'name' => 'Delete Salary Structure Components',
                    'url' => 'structure/delete',
                    'action' => 'delete',
                    'show' => 0,
                    'order' => 4,
                    'status' => 1,
                ],
            ],
        ],

        [
            'name' => 'Salary Rules',
            'show' => 1,
            'scope' => json_encode([Module::SCOPE_COMMON]),
            'order' => 3,
            'status' => 1,
            'menu' => [
                [
                    'name' => 'New Salary Rule',
                    'url' => 'rule/add',
                    'action' => 'add',
                    'order' => 1,
                    'show' => 1,
                    'status' => 1,
                ],
                [
                    'name' => 'Salary Rules',
                    'url' => 'rules',
                    'action' => 'list',
                    'order' => 2,
                    'show' => 1,
                    'status' => 1,
                ],
                [
                    'name' => 'Edit Salary Rule',
                    'url' => 'rule/edit',
                    'action' => 'edit',
                    'order' => 3,
                    'show' => 0,
                    'status' => 1,
                ],
                [
                    'name' => 'Delete Salary Rule',
                    'url' => 'rule/delete',
                    'action' => 'delete',
                    'order' => 5,
                    'show' => 0,
                    'status' => 1,
                ],
                [
                    'name' => 'View Salary Rule',
                    'url' => 'rule/view',
                    'action' => 'view',
                    'order' => 6,
                    'show' => 0,
                    'status' => 1,
                ],
            ],
        ],

        [
            'name' => 'Salary',
            'show' => 1,
            'scope' => json_encode([Module::SCOPE_COMMON]),
            'order' => 4,
            'status' => 1,
            'menu' => [
                [
                    'name' => 'Generate Salary',
                    'url' => 'salary-generate',
                    'action' => 'add',
                    'order' => 1,
                    'show' => 0,
                    'status' => 1,
                ],
                [
                    'name' => 'Pending Salaries',
                    'url' => 'pending-salaries',
                    'action' => 'list',
                    'order' => 2,
                    'show' => 1,
                    'status' => 1,
                ],
                [
                    'name' => 'Approved Salaries',
                    'url' => 'approved-salaries',
                    'action' => 'list',
                    'order' => 2,
                    'show' => 1,
                    'status' => 1,
                ],
                [
                    'name' => 'Salary Approve',
                    'url' => 'salary/approve',
                    'action' => 'edit',
                    'order' => 3,
                    'show' => 0,
                    'status' => 1,
                ],
                [
                    'name' => 'Salary Pay',
                    'url' => 'salary/pay',
                    'action' => 'edit',
                    'order' => 3,
                    'show' => 0,
                    'status' => 1,
                ],
                [
                    'name' => 'Salary Payslip',
                    'url' => 'salary/payslip',
                    'action' => 'view',
                    'order' => 4,
                    'show' => 0,
                    'status' => 1,
                ],
                [
                    'name' => 'Payslip Print',
                    'url' => 'salary/payslip/print',
                    'action' => 'export',
                    'order' => 5,
                    'show' => 0,
                    'status' => 1,
                ],
                [
                    'name' => 'View Salary',
                    'url' => 'salary/view',
                    'action' => 'view',
                    'order' => 6,
                    'show' => 0,
                    'status' => 1,
                ],
                [
                    'name' => 'Delete Salary',
                    'url' => 'salary/delete',
                    'action' => 'delete',
                    'order' => 7,
                    'show' => 0,
                    'status' => 1,
                ],
            ],
        ],
    ],
];
