<?php

use \App\Models\Module;

return [
    'name' => 'Organization',
    'url' => 'organization',
    'scope' => json_encode([Module::SCOPE_ADMIN, Module::SCOPE_COMPANY]),
    'icon' => 'fa fa-building-o',
    'status' => 1,
    'order' => 4,

    //Submodules
    'submodules' => [
        [
            'name' => 'Departments',
            'show' => 0,
            'order' => 1,
            'scope' => json_encode([Module::SCOPE_COMMON]),
            'status' => 1,
            'menu' => [
                [
                    'name' => 'New Department',
                    'url' => 'department/add',
                    'action' => 'add',
                    'show' => 0,
                    'order' => 1,
                    'status' => 1,
                ],
                [
                    'name' => 'Departments',
                    'url' => 'departments',
                    'action' => 'list',
                    'show' => 1,
                    'order' => 2,
                    'status' => 1,
                ],
                [
                    'name' => 'Edit Department',
                    'url' => 'department/edit',
                    'action' => 'edit',
                    'show' => 0,
                    'order' => 3,
                    'status' => 1,
                ],
                [
                    'name' => 'Trash Department',
                    'url' => 'department/trash',
                    'action' => 'trash',
                    'show' => 0,
                    'order' => 5,
                    'status' => 1,
                ],
                [
                    'name' => 'Restore Department',
                    'url' => 'department/restore',
                    'action' => 'restore',
                    'show' => 0,
                    'order' => 6,
                    'status' => 1,
                ],
                [
                    'name' => 'Delete Department',
                    'url' => 'department/delete',
                    'action' => 'delete',
                    'show' => 0,
                    'order' => 8,
                    'status' => 1,
                ],
            ],
        ],

        [
            'name' => 'Designations',
            'show' => 0,
            'order' => 2,
            'scope' => json_encode([Module::SCOPE_COMMON]),
            'status' => 1,
            'menu' => [
                [
                    'name' => 'New Designation',
                    'url' => 'designation/add',
                    'action' => 'add',
                    'order' => 1,
                    'show' => 0,
                    'status' => 1,
                ],
                [
                    'name' => 'Designations',
                    'url' => 'designations',
                    'action' => 'list',
                    'order' => 2,
                    'show' => 1,
                    'status' => 1,
                ],
                [
                    'name' => 'Edit Designation',
                    'url' => 'designation/edit',
                    'action' => 'edit',
                    'order' => 3,
                    'show' => 0,
                    'status' => 1,
                ],
                [
                    'name' => 'Trash Designation',
                    'url' => 'designation/trash',
                    'action' => 'trash',
                    'order' => 6,
                    'show' => 0,
                    'status' => 1,
                ],
                [
                    'name' => 'Restore Designation',
                    'url' => 'designation/restore',
                    'action' => 'restore',
                    'order' => 7,
                    'show' => 0,
                    'status' => 1,
                ],
                [
                    'name' => 'Delete Designation',
                    'url' => 'designation/delete',
                    'action' => 'delete',
                    'order' => 8,
                    'show' => 0,
                    'status' => 1,
                ],
            ],
        ],

        [
            'name' => 'Attendance Deduction Policy',
            'show' => 0,
            'scope' => json_encode([Module::SCOPE_COMMON]),
            'order' => 3,
            'status' => 1,
            'menu' => [
                [
                    'name' => 'New Deduction Policy',
                    'url' => 'deduction-policy/add',
                    'action' => 'add',
                    'show' => 0,
                    'order' => 1,
                    'status' => 1,
                ],
                [
                    'name' => 'Attendance Deduction Policy',
                    'url' => 'deduction-policies',
                    'action' => 'list',
                    'show' => 1,
                    'order' => 2,
                    'status' => 1,
                ],
                [
                    'name' => 'Edit Deduction Policy',
                    'url' => 'deduction-policy/edit',
                    'action' => 'edit',
                    'show' => 0,
                    'order' => 3,
                    'status' => 1,
                ],
                [
                    'name' => 'Trash Deduction Policy',
                    'url' => 'deduction-policy/trash',
                    'action' => 'trash',
                    'show' => 0,
                    'order' => 6,
                    'status' => 1,
                ],
                [
                    'name' => 'Restore Deduction Policy',
                    'url' => 'deduction-policy/restore',
                    'action' => 'restore',
                    'show' => 0,
                    'order' => 7,
                    'status' => 1,
                ],
                [
                    'name' => 'Delete Deduction Policy',
                    'url' => 'deduction-policy/delete',
                    'action' => 'delete',
                    'show' => 0,
                    'order' => 8,
                    'status' => 1,
                ],
            ],
        ],

        //Leave Policy
        [
            'name' => 'Leave Policy',
            'show' => 0,
            'scope' => json_encode([Module::SCOPE_COMMON]),
            'order' => 3,
            'status' => 1,
            'menu' => [
                [
                    'name' => 'New Leave Policy',
                    'url' => 'leave-policy/add',
                    'action' => 'add',
                    'show' => 0,
                    'order' => 1,
                    'status' => 1,
                ],
                [
                    'name' => 'Leave Policy',
                    'url' => 'leave-policies',
                    'action' => 'list',
                    'show' => 1,
                    'order' => 2,
                    'status' => 1,
                ],
                [
                    'name' => 'Edit Leave Policy',
                    'url' => 'leave-policy/edit',
                    'action' => 'edit',
                    'show' => 0,
                    'order' => 3,
                    'status' => 1,
                ],
                [
                    'name' => 'Trash Leave Policy',
                    'url' => 'leave-policy/trash',
                    'action' => 'trash',
                    'show' => 0,
                    'order' => 5,
                    'status' => 1,
                ],
                [
                    'name' => 'Restore Leave Policy',
                    'url' => 'leave-policy/restore',
                    'action' => 'restore',
                    'show' => 0,
                    'order' => 6,
                    'status' => 1,
                ],
                [
                    'name' => 'Delete Leave Policy',
                    'url' => 'leave-policy/delete',
                    'action' => 'delete',
                    'show' => 0,
                    'order' => 7,
                    'status' => 1,
                ],
            ],
        ],
    ],
];
