<?php

use \App\Models\Module;

return [
    'name' => 'Component Settings',
    'url' => 'component-settings',
    'scope' => json_encode([Module::SCOPE_COMMON]),
    'icon' => 'fa fa-cog',
    'status' => 1,
    'order' => 0,

    //Submodules
    'submodules' => [
        //Employee Types
        [
            'name' => 'Employment Type',
            'show' => 0,
            'order' => 1,
            'scope' => json_encode([Module::SCOPE_ADMIN, Module::SCOPE_COMPANY]),
            'status' => 1,
            'menu' => [
                [
                    'name' => 'New Employment Type',
                    'url' => 'employment-type/add',
                    'action' => 'add',
                    'show' => 0,
                    'order' => 1,
                    'status' => 1,
                ],
                [
                    'name' => 'Employment Types',
                    'url' => 'employment-types',
                    'action' => 'list',
                    'show' => 1,
                    'order' => 2,
                    'status' => 1,
                ],
                [
                    'name' => 'Edit Employment Types',
                    'url' => 'employment-type/edit',
                    'action' => 'edit',
                    'show' => 0,
                    'order' => 3,
                    'status' => 1,
                ],
                [
                    'name' => 'Trash Employment Types',
                    'url' => 'employment-type/trash',
                    'action' => 'trash',
                    'show' => 0,
                    'order' => 4,
                    'status' => 1,
                ],
                [
                    'name' => 'Restore Employment Types',
                    'url' => 'employment-type/restore',
                    'action' => 'restore',
                    'show' => 0,
                    'order' => 5,
                    'status' => 1,
                ],
                [
                    'name' => 'Delete Employment Types',
                    'url' => 'employment-type/delete',
                    'action' => 'delete',
                    'show' => 0,
                    'order' => 7,
                    'status' => 1,
                ],
            ],
        ],

        //leave-types
        [
            'name' => 'Leave Types',
            'show' => 0,
            'order' => 3,
            'scope' => json_encode([Module::SCOPE_COMMON]),
            'status' => 1,
            'menu' => [
                [
                    'name' => 'New Leave Type',
                    'url' => 'leave-type/add',
                    'action' => 'add',
                    'show' => 0,
                    'order' => 1,
                    'status' => 1,
                ],
                [
                    'name' => 'Leave Types',
                    'url' => 'leave-types',
                    'action' => 'list',
                    'show' => 1,
                    'order' => 2,
                    'status' => 1,
                ],
                [
                    'name' => 'Edit Leave Type',
                    'url' => 'leave-type/edit',
                    'action' => 'edit',
                    'show' => 0,
                    'order' => 3,
                    'status' => 1,
                ],
                [
                    'name' => 'Trash Leave Type',
                    'url' => 'leave-type/trash',
                    'action' => 'trash',
                    'show' => 0,
                    'order' => 4,
                    'status' => 1,
                ],
                [
                    'name' => 'Restore Leave Type',
                    'url' => 'leave-type/restore',
                    'action' => 'restore',
                    'show' => 0,
                    'order' => 5,
                    'status' => 1,
                ],
                [
                    'name' => 'Delete Leave Type',
                    'url' => 'leave-type/delete',
                    'action' => 'delete',
                    'show' => 0,
                    'order' => 6,
                    'status' => 1,
                ],
            ],
        ],

        //Tax setting menus
        [
            'name' => 'Taxes',
            'show' => 0,
            'scope' => json_encode([Module::SCOPE_COMMON]),
            'order' => 4,
            'status' => 1,
            'menu' => [
                [
                    'name' => 'New Tax',
                    'url' => 'tax/add',
                    'action' => 'add',
                    'show' => 0,
                    'order' => 1,
                    'status' => 1,
                ],
                [
                    'name' => 'Taxes',
                    'url' => 'taxes',
                    'action' => 'list',
                    'show' => 1,
                    'order' => 2,
                    'status' => 1,
                ],
                [
                    'name' => 'Edit Tax',
                    'url' => 'tax/edit',
                    'action' => 'edit',
                    'show' => 0,
                    'order' => 3,
                    'status' => 1,
                ],
                [
                    'name' => 'Trash Tax',
                    'url' => 'tax/trash',
                    'action' => 'trash',
                    'show' => 0,
                    'order' => 5,
                    'status' => 1,
                ],
                [
                    'name' => 'Restore Tax',
                    'url' => 'tax/restore',
                    'action' => 'restore',
                    'show' => 0,
                    'order' => 6,
                    'status' => 1,
                ],
                [
                    'name' => 'Delete Tax',
                    'url' => 'tax/delete',
                    'action' => 'delete',
                    'show' => 0,
                    'order' => 7,
                    'status' => 1,
                ],
            ],
        ],

        //Shift
        [
            'name' => 'Working Shift',
            'show' => 0,
            'order' => 2,
            'scope' => json_encode([Module::SCOPE_ADMIN, Module::SCOPE_COMPANY]),
            'status' => 1,
            'menu' => [
                [
                    'name' => 'New Shift',
                    'url' => 'shift/add',
                    'action' => 'add',
                    'show' => 0,
                    'order' => 1,
                    'status' => 1,
                ],
                [
                    'name' => 'Working Shifts',
                    'url' => 'shifts',
                    'action' => 'list',
                    'show' => 1,
                    'order' => 2,
                    'status' => 1,
                ],
                [
                    'name' => 'Edit Shift',
                    'url' => 'shift/edit',
                    'action' => 'edit',
                    'show' => 0,
                    'order' => 3,
                    'status' => 1,
                ],
                [
                    'name' => 'Trash Shift',
                    'url' => 'shift/trash',
                    'action' => 'trash',
                    'show' => 0,
                    'order' => 4,
                    'status' => 1,
                ],
                [
                    'name' => 'Restore Shift',
                    'url' => 'shift/restore',
                    'action' => 'restore',
                    'show' => 0,
                    'order' => 5,
                    'status' => 1,
                ],
                [
                    'name' => 'Delete Shift',
                    'url' => 'shift/delete',
                    'action' => 'delete',
                    'show' => 0,
                    'order' => 7,
                    'status' => 1,
                ],
            ],
        ],

        //Holidays
        [
            'name' => 'Holidays',
            'show' => 0,
            'order' => 6,
            'scope' => json_encode([Module::SCOPE_COMMON, Module::SCOPE_EMPLOYEE]),
            'status' => 1,
            'menu' => [
                [
                    'name' => 'New Holiday',
                    'url' => 'holiday/add',
                    'action' => 'add',
                    'show' => 0,
                    'order' => 1,
                    'status' => 1,
                ],
                [
                    'name' => 'Holidays',
                    'url' => 'holidays',
                    'action' => 'list',
                    'show' => 1,
                    'order' => 2,
                    'status' => 1,
                ],
                [
                    'name' => 'Trash Holiday',
                    'url' => 'holiday/trash',
                    'action' => 'trash',
                    'show' => 0,
                    'order' => 7,
                    'status' => 1,
                ],
                [
                    'name' => 'Restore Holiday',
                    'url' => 'holiday/restore',
                    'action' => 'restore',
                    'show' => 0,
                    'order' => 7,
                    'status' => 1,
                ],
                [
                    'name' => 'Delete Holiday',
                    'url' => 'holiday/delete',
                    'action' => 'delete',
                    'show' => 0,
                    'order' => 8,
                    'status' => 1,
                ],
            ],
        ],

        //Job Categories
        [
            'name' => 'Job Category',
            'show' => 0,
            'order' => 8,
            'scope' => json_encode([Module::SCOPE_COMMON]),
            'status' => 1,
            'menu' => [
                [
                    'name' => 'New Job Category',
                    'url' => 'job-category/add',
                    'action' => 'add',
                    'show' => 0,
                    'order' => 1,
                    'status' => 1,
                ],
                [
                    'name' => 'Job Categories',
                    'url' => 'job-categories',
                    'action' => 'list',
                    'show' => 1,
                    'order' => 2,
                    'status' => 1,
                ],
                [
                    'name' => 'Edit Category',
                    'url' => 'job-category/edit',
                    'action' => 'edit',
                    'show' => 0,
                    'order' => 3,
                    'status' => 1,
                ],
                [
                    'name' => 'Trash',
                    'url' => 'job-category/trash',
                    'action' => 'trash',
                    'show' => 0,
                    'order' => 7,
                    'status' => 1,
                ],
                [
                    'name' => 'Restore',
                    'url' => 'job-category/restore',
                    'action' => 'restore',
                    'show' => 0,
                    'order' => 7,
                    'status' => 1,
                ],
                [
                    'name' => 'Delete',
                    'url' => 'job-category/delete',
                    'action' => 'delete',
                    'show' => 0,
                    'order' => 8,
                    'status' => 1,
                ],
            ],
        ],


    ],

];
