<?php

use \App\Models\Module;

return [
    'name' => 'Employee Information',
    'url' => 'employee',
    'scope' => json_encode([Module::SCOPE_COMMON, Module::SCOPE_EMPLOYEE]),
    'icon' => 'fa fa-user',
    'status' => 1,
    'order' => 5,

    //Submodules
    'submodules' => [
        [
            'name' => 'Employees',
            'show' => 0,
            'order' => 1,
            'scope' => json_encode([Module::SCOPE_COMMON, Module::SCOPE_EMPLOYEE]),
            'status' => 1,
            'menu' => [
                [
                    'name' => 'New Employee',
                    'url' => 'employee/add',
                    'action' => 'add',
                    'show' => 1,
                    'order' => 1,
                    'status' => 1,
                ],
                [
                    'name' => 'Employees',
                    'url' => 'employees',
                    'action' => 'list',
                    'show' => 1,
                    'order' => 2,
                    'status' => 1,
                ],
                [
                    'name' => 'Inactive Employees',
                    'url' => 'employees/inactive',
                    'action' => 'list',
                    'show' => 1,
                    'order' => 3,
                    'status' => 1,
                ],
                [
                    'name' => 'Edit Employment information',
                    'url' => 'employment/edit',
                    'action' => 'editEmployment',
                    'show' => 0,
                    'order' => 4,
                    'status' => 1,
                ],
                [
                    'name' => 'Edit Personal Information',
                    'url' => 'personal/edit',
                    'action' => 'editPersonal',
                    'show' => 0,
                    'order' => 5,
                    'status' => 1,
                ],
                //Educations
                [
                    'name' => 'New Education',
                    'url' => 'education/add',
                    'action' => 'addEducation',
                    'show' => 0,
                    'order' => 6,
                    'status' => 1,
                ],
                [
                    'name' => 'Employee Educations',
                    'url' => 'education/list',
                    'action' => 'listEducation',
                    'show' => 0,
                    'order' => 7,
                    'status' => 1,
                ],
                [
                    'name' => 'Edit Education',
                    'url' => 'education/edit',
                    'action' => 'editEducation',
                    'show' => 0,
                    'order' => 8,
                    'status' => 1,
                ],
                [
                    'name' => 'Approve Education',
                    'url' => 'education/approve',
                    'action' => 'approveEducation',
                    'show' => 0,
                    'order' => 10,
                    'status' => 1,
                ],
                [
                    'name' => 'Delete Education',
                    'url' => 'education/delete',
                    'action' => 'deleteEducation',
                    'show' => 0,
                    'order' => 11,
                    'status' => 1,
                ],
                //Address
                [
                    'name' => 'New Address',
                    'url' => 'address/add',
                    'action' => 'addAddress',
                    'show' => 0,
                    'order' => 12,
                    'status' => 1,
                ],
                [
                    'name' => 'Employee Addresses',
                    'url' => 'address/list',
                    'action' => 'listAddress',
                    'show' => 0,
                    'order' => 15,
                    'status' => 1,
                ],
                [
                    'name' => 'Edit Address',
                    'url' => 'address/edit',
                    'action' => 'editAddress',
                    'show' => 0,
                    'order' => 17,
                    'status' => 1,
                ],
                [
                    'name' => 'View Address',
                    'url' => 'address/view',
                    'action' => 'viewAddress',
                    'show' => 0,
                    'order' => 18,
                    'status' => 1,
                ],
                [
                    'name' => 'Delete Address',
                    'url' => 'address/delete',
                    'action' => 'deleteAddress',
                    'show' => 0,
                    'order' => 21,
                    'status' => 1,
                ],

                //Documents
                [
                    'name' => 'New Document',
                    'url' => 'document/add',
                    'action' => 'addDocument',
                    'show' => 0,
                    'order' => 22,
                    'status' => 1,
                ],
                [
                    'name' => 'Documents',
                    'url' => 'document/list',
                    'action' => 'listDocument',
                    'show' => 0,
                    'order' => 23,
                    'status' => 1,
                ],
                [
                    'name' => 'Edit Document',
                    'url' => 'document/edit',
                    'action' => 'editDocument',
                    'show' => 0,
                    'order' => 25,
                    'status' => 1,
                ],
                [
                    'name' => 'Delete Document',
                    'url' => 'document/delete',
                    'action' => 'deleteDocument',
                    'show' => 0,
                    'order' => 27,
                    'status' => 1,
                ],
                [
                    'name' => 'Export Document',
                    'url' => 'document/export',
                    'action' => 'exportDocument',
                    'show' => 0,
                    'order' => 29,
                    'status' => 1,
                ],
                [
                    'name' => 'Approve Document',
                    'url' => 'document/approve',
                    'action' => 'approveDocument',
                    'show' => 0,
                    'order' => 31,
                    'status' => 1,
                ],
                //document end
                [
                    'name' => 'View Employee',
                    'url' => 'employee/view',
                    'action' => 'view',
                    'show' => 0,
                    'order' => 35,
                    'status' => 1,
                ],
                [
                    'name' => 'Export Employee',
                    'url' => 'employee/export',
                    'action' => 'export',
                    'show' => 0,
                    'order' => 37,
                    'status' => 1,
                ],
                [
                    'name' => 'Import Employee',
                    'url' => 'employee/import',
                    'action' => 'import',
                    'show' => 0,
                    'order' => 39,
                    'status' => 1,
                ],

                [
                    'name' => 'Trash Employee',
                    'url' => 'employee/trash',
                    'action' => 'trash',
                    'show' => 0,
                    'order' => 33,
                    'status' => 1,
                ],
                [
                    'name' => 'Restore Employee',
                    'url' => 'employee/restore',
                    'action' => 'restore',
                    'show' => 0,
                    'order' => 34,
                    'status' => 1,
                ],
                [
                    'name' => 'Delete Employee',
                    'url' => 'employee/delete',
                    'action' => 'delete',
                    'show' => 0,
                    'order' => 40,
                    'status' => 1,
                ],
            ],
        ],
    ],

];
