<?php

use \App\Models\Module;

return [
    'name' => 'User Management',
    'url' => 'user-managements',
    'scope' => json_encode([Module::SCOPE_COMPANY, Module::SCOPE_ADMIN]),
    'icon' => 'fa fa-users',
    'status' => 1,
    'order' => 1,
    //Submodules
    'submodules' => [
        [
            'name' => 'Roles',
            'show' => 1,
            'scope' => json_encode([Module::SCOPE_COMMON]),
            'order' => 1,
            'status' => 1,
            'menu' => [
                [
                    'name' => 'Roles',
                    'url' => 'roles',
                    'action' => 'list',
                    'show' => 1,
                    'order' => 2,
                    'status' => 1,
                ],
                [
                    'name' => 'New Role',
                    'url' => 'role/add',
                    'action' => 'add',
                    'show' => 1,
                    'order' => 1,
                    'status' => 1,
                ],
                [
                    'name' => 'Edit Role',
                    'url' => 'role/edit',
                    'action' => 'edit',
                    'show' => 0,
                    'order' => 3,
                    'status' => 1,
                ],
                [
                    'name' => 'Trash Role',
                    'url' => 'role/trash',
                    'action' => 'trash',
                    'show' => 0,
                    'order' => 4,
                    'status' => 1,
                ],
                [
                    'name' => 'Restore Role',
                    'url' => 'role/restore',
                    'action' => 'restore',
                    'show' => 0,
                    'order' => 5,
                    'status' => 1,
                ],
                [
                    'name' => 'Delete Role',
                    'url' => 'role/delete',
                    'action' => 'delete',
                    'show' => 0,
                    'order' => 7,
                    'status' => 1,
                ],
            ],
        ],

        [
            'name' => 'Users',
            'show' => 0,
            'scope' => json_encode([Module::SCOPE_COMMON]),
            'order' => 2,
            'status' => 1,
            'menu' => [
                [
                    'name' => 'Users',
                    'url' => 'users',
                    'action' => 'list',
                    'order' => 2,
                    'show' => 1,
                    'status' => 1,
                ],
                [
                    'name' => 'New User',
                    'url' => 'user/add',
                    'action' => 'add',
                    'order' => 1,
                    'show' => 0,
                    'status' => 1,
                ],
                [
                    'name' => 'Edit User',
                    'url' => 'user/edit',
                    'action' => 'edit',
                    'order' => 3,
                    'show' => 0,
                    'status' => 1,
                ],
                [
                    'name' => 'View User',
                    'url' => 'user/view',
                    'action' => 'view',
                    'order' => 4,
                    'show' => 0,
                    'status' => 1,
                ],
                [
                    'name' => 'Export User',
                    'url' => 'user/export',
                    'action' => 'export',
                    'order' => 5,
                    'show' => 0,
                    'status' => 1,
                ],
                [
                    'name' => 'Trash User',
                    'url' => 'user/trash',
                    'action' => 'trash',
                    'order' => 6,
                    'show' => 0,
                    'status' => 1,
                ],
                [
                    'name' => 'Restore User',
                    'url' => 'user/restore',
                    'action' => 'restore',
                    'order' => 7,
                    'show' => 0,
                    'status' => 1,
                ],
                [
                    'name' => 'Delete User',
                    'url' => 'user/delete',
                    'action' => 'delete',
                    'order' => 8,
                    'show' => 0,
                    'status' => 1,
                ],
            ],
        ],

        [
            'name' => 'Password Reset',
            'show' => 0,
            'scope' => json_encode([Module::SCOPE_COMMON]),
            'order' => 3,
            'status' => 1,
            'menu' => [
                [
                    'name' => 'Password Reset',
                    'url' => 'user/password-reset',
                    'action' => 'list',
                    'order' => 3,
                    'show' => 1,
                    'status' => 1,
                ],
                [
                    'name' => 'Update Password',
                    'url' => 'user/update-password',
                    'action' => 'add',
                    'order' => 1,
                    'show' => 0,
                    'status' => 1,
                ],
            ],
        ],
    ],
];
