<?php

use \App\Models\Module;

return [
    'name' => 'Recruitment',
    'url' => 'recruitment',
    'scope' => json_encode([Module::SCOPE_COMMON, Module::SCOPE_EMPLOYEE]),
    'icon' => 'fa fa-briefcase',
    'status' => 1,
    'order' => 9,

    //Submodules
    'submodules' => [
        [
            'name' => 'Job Posting',
            'show' => 0,
            'order' => 1,
            'scope' => json_encode([Module::SCOPE_COMMON, Module::SCOPE_EMPLOYEE]),
            'status' => 1,
            'menu' => [
                [
                    'name' => 'New Job',
                    'url' => 'job-posting/add',
                    'action' => 'add',
                    'show' => 0,
                    'order' => 1,
                    'status' => 1,
                ],
                [
                    'name' => 'Job Posting',
                    'url' => 'job-posting',
                    'action' => 'list',
                    'show' => 1,
                    'order' => 2,
                    'status' => 1,
                ],
                [
                    'name' => 'Edit Job',
                    'url' => 'job-posting/edit',
                    'action' => 'edit',
                    'show' => 0,
                    'order' => 4,
                    'status' => 1,
                ],
                [
                    'name' => 'Delete Job',
                    'url' => 'job-posting/delete',
                    'action' => 'delete',
                    'show' => 0,
                    'order' => 5,
                    'status' => 1,
                ],
                [
                    'name' => 'Trash',
                    'url' => 'job-posting/trash',
                    'action' => 'trash',
                    'show' => 0,
                    'order' => 6,
                    'status' => 1,
                ],
                [
                    'name' => 'Restore',
                    'url' => 'job-posting/restore',
                    'action' => 'restore',
                    'show' => 0,
                    'order' => 7,
                    'status' => 1,
                ],
                [
                    'name' => 'View Job',
                    'url' => 'job-posting/view',
                    'action' => 'view',
                    'show' => 0,
                    'order' => 8,
                    'status' => 1,
                ],
            ],
        ],

        [
            'name' => 'Applications',
            'show' => 0,
            'order' => 2,
            'scope' => json_encode([Module::SCOPE_COMMON, Module::SCOPE_EMPLOYEE]),
            'status' => 1,
            'menu' => [
                [
                    'name' => 'Edit Application',
                    'url' => 'application/edit',
                    'action' => 'edit',
                    'show' => 0,
                    'order' => 1,
                    'status' => 1,
                ],
                [
                    'name' => 'Applications',
                    'url' => 'applications',
                    'action' => 'list',
                    'show' => 1,
                    'order' => 2,
                    'status' => 1,
                ],
                [
                    'name' => 'Rejected Application',
                    'url' => 'application/rejected',
                    'action' => 'list',
                    'show' => 0,
                    'order' => 5,
                    'status' => 1,
                ],
                [
                    'name' => 'View Application',
                    'url' => 'application/view',
                    'action' => 'view',
                    'show' => 0,
                    'order' => 5,
                    'status' => 1,
                ],
                [
                    'name' => 'Trash',
                    'url' => 'application/trash',
                    'action' => 'trash',
                    'show' => 0,
                    'order' => 6,
                    'status' => 1,
                ],
                [
                    'name' => 'Restore',
                    'url' => 'application/restore',
                    'action' => 'restore',
                    'show' => 0,
                    'order' => 7,
                    'status' => 1,
                ],
                [
                    'name' => 'Delete',
                    'url' => 'application/delete',
                    'action' => 'delete',
                    'show' => 0,
                    'order' => 8,
                    'status' => 1,
                ],
            ],
        ],

        [
            'name' => 'Interview',
            'show' => 0,
            'order' => 3,
            'scope' => json_encode([Module::SCOPE_COMMON, Module::SCOPE_EMPLOYEE]),
            'status' => 1,
            'menu' => [
                [
                    'name' => 'New Interview',
                    'url' => 'interview/add',
                    'action' => 'add',
                    'show' => 0,
                    'order' => 1,
                    'status' => 1,
                ],
                [
                    'name' => 'Interviews',
                    'url' => 'interviews',
                    'action' => 'list',
                    'show' => 1,
                    'order' => 2,
                    'status' => 1,
                ],
                [
                    'name' => 'Edit Interview',
                    'url' => 'interview/edit',
                    'action' => 'edit',
                    'show' => 0,
                    'order' => 2,
                    'status' => 1,
                ],
                [
                    'name' => 'Delete Interview',
                    'url' => 'interview/delete',
                    'action' => 'delete',
                    'show' => 0,
                    'order' => 5,
                    'status' => 1,
                ],
                [
                    'name' => 'Trash',
                    'url' => 'interview/trash',
                    'action' => 'trash',
                    'show' => 0,
                    'order' => 6,
                    'status' => 1,
                ],
                [
                    'name' => 'Restore',
                    'url' => 'interview/restore',
                    'action' => 'restore',
                    'show' => 0,
                    'order' => 7,
                    'status' => 1,
                ],
                [
                    'name' => 'Delete',
                    'url' => 'interview/delete',
                    'action' => 'delete',
                    'show' => 0,
                    'order' => 8,
                    'status' => 1,
                ],
                [
                    'name' => 'View Interview',
                    'url' => 'interview/view',
                    'action' => 'view',
                    'show' => 0,
                    'order' => 9,
                    'status' => 1,
                ],
            ],
        ],

        [
            'name' => 'Job Offer',
            'show' => 0,
            'order' => 10,
            'scope' => json_encode([Module::SCOPE_COMMON, Module::SCOPE_EMPLOYEE]),
            'status' => 1,
            'menu' => [
                [
                    'name' => 'New Offer',
                    'url' => 'offer/add',
                    'action' => 'add',
                    'show' => 0,
                    'order' => 1,
                    'status' => 1,
                ],
                [
                    'name' => 'Offer Job',
                    'url' => 'offers',
                    'action' => 'list',
                    'show' => 1,
                    'order' => 2,
                    'status' => 1,
                ],
                [
                    'name' => 'Edit Offer',
                    'url' => 'offer/edit',
                    'action' => 'edit',
                    'show' => 0,
                    'order' => 2,
                    'status' => 1,
                ],
                [
                    'name' => 'Delete Offer',
                    'url' => 'offer/delete',
                    'action' => 'delete',
                    'show' => 0,
                    'order' => 5,
                    'status' => 1,
                ],
                [
                    'name' => 'Trash',
                    'url' => 'offer/trash',
                    'action' => 'trash',
                    'show' => 0,
                    'order' => 6,
                    'status' => 1,
                ],
                [
                    'name' => 'Restore',
                    'url' => 'offer/restore',
                    'action' => 'restore',
                    'show' => 0,
                    'order' => 7,
                    'status' => 1,
                ],
                [
                    'name' => 'Delete',
                    'url' => 'offer/delete',
                    'action' => 'delete',
                    'show' => 0,
                    'order' => 8,
                    'status' => 1,
                ],
                [
                    'name' => 'View Offer',
                    'url' => 'offer/view',
                    'action' => 'view',
                    'show' => 0,
                    'order' => 9,
                    'status' => 1,
                ],
            ],
        ],
    ],

];
